### ISSUE TITLE
Rider stats calculation

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#106]
Depending on which screen you are on, the campaigns and deliveries numbers for riders are different. 
https://dispatch.bikebrigade.ca/stats/leaderboard Chad 878/2132
https://dispatch.bikebrigade.ca/riders/3238 Chad 872/2119

Does one pull from all assigned rides including the future and the other only things in the past?

**Comment by mveytsman** [comment]
You were exactly right @chadmohr - I made the leaderboard not count future campaigns unless you're explicitly selecting dates in the future
