### ISSUE TITLE
Rider itinerary page (basic)

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#136]
A Rider should be able to see all of the deliveries they are signed up for.

Right now we have "Delivery details pages" that work for a single delivery. 

We would like an "itinerary" that gives you a list of these ordered by day.

The "basic" version can just aggregate data (e.g. "You are delivering 10 items for 5 campaigns"), and link to the existing iteneraries.

Also note that we won't show the rides later this week to people because of how we dispatch - so we want some "Beta" copy.

**Comment by chadmohr** [comment]
This is super basic, but its a start - https://xd.adobe.com/view/cbf01281-7c58-4aa0-b403-a9ef063e064c-9ea3/

**Comment by mveytsman** [comment]
@nathan-louie to take this on this week 

- for testing, you can create a couple campaigns on the same day and assign a given rider to deliveries
- We don't have a rider per user yet , so we can call it "My profile" for testing but keep a hardcoded rider id
- Right now the delivery pages are all public with a random token in the URL, we will want to put them behind login, with a more reasonable url.

**Comment by mveytsman** [comment]
As discussed:

- add some buttons to browse daily iteneraries by date.
- @mveytsman to ship enough of #135 to enable @nathan-louie to write integration tests.

**Comment by chadmohr** [comment]
I am now recalling that previously we discussed how it may confuse riders to see itineraries for additional days because we generally only dispatch one day in advance. So riders would very likely end up seeing empty future days when in fact they have signe dup for something.

**Comment by mveytsman** [comment]
I remember this conversation.

I feel like since we're shipping this with a slow rollout we can mitigate it with some copy / block you from going into the future if need be.

Still think that's it's worth to have as we test/roll things out...

**Comment by mveytsman** [comment]
@teesloane to 🚀 this

- [ ] Integration tests around it
- [ ] Improve copy around how it's beta 
- [ ] Add to sidebar for Riders
- [ ] Make it the default page when you log in as a rider
