### ISSUE TITLE
Rider itinerary page (redesign)

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#138]
After #136 we should have a page specifically designed around showing a rider their full day.

This should have some good mocks around it.

**Comment by teesloane** [comment]
This is completed, if i understand correctly; below is a rider's itinerary page:

<img width="1745" alt="image" src="https://github.com/bikebrigade/dispatch/assets/12987958/be074c2a-2697-41f9-aa30-d3bf4f1117e4">
