### ISSUE TITLE
Riders sign up for a specific campaign via app

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#140]
Mocks for this https://xd.adobe.com/view/e64dceb0-2df2-400f-8971-405ce662631f-b31e/screen/ef229902-9870-4af9-8024-77d66ec81fd7/

Dispatcher side at #139

**Comment by chadmohr** [comment]
I cleaned up the mocks by removing screens not relevant to this task. Also left some comments in them.
