### ISSUE TITLE
Option to hide items when editing a program

### ISSUE THREAD

**Issue by nathan-louie** [bikebrigade/dispatch#177]
![image](https://user-images.githubusercontent.com/53024905/182922557-11a29345-a810-4dd9-b813-3d8d81f30898.png)

**Comment by mveytsman** [comment]
Noting that we may actually want to hide the item instead of delete it, as to not mess up previous stat around items.

**Comment by mveytsman** [comment]
Steps:

- [ ] Add a hidden field to `Item`
- [ ] Show/edit hidden state when editing items
- [ ] Hide hidden items when showing items in the delivery page

**Comment by mveytsman** [comment]
Closed in #179
