### ISSUE TITLE
Task count not rendering in messaging?

### ISSUE THREAD

**Issue by jennaleeb** [bikebrigade/dispatch#186]
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8824824/184642628-aa76bc4b-f31b-4cb0-bdd7-61606f9ccf91.png">

E.g. https://dispatch.bikebrigade.ca/campaigns/3235/messaging

**Comment by jennaleeb** [comment]
Oops my bad that rider didn't have anything assigned!

**Comment by mveytsman** [comment]
[I removed the screenshot for privacy reasons]

**Comment by jennaleeb** [comment]
Ugh sorry, not on my game this morning.
