### ISSUE TITLE
Standardize on underscores for event names

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#202]
We have events `"filter_riders"` and `"add-item"`

We should standardize on them all being underscored (or dashed?) 

@teesloane do you have a standard convention in your codebases?

**Comment by teesloane** [comment]
Nah, no standard — but the same thing is happening - a mix of `-` and `_`. I'd be inclined to do just underscores since kebab case isn't possible in Elixir but `¯\_(ツ)_/¯`

**Comment by mveytsman** [comment]
Closed in #206
