### ISSUE TITLE
Opportunities page edit link

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#214]

**Comment by chadmohr** [comment]
Many screen widths require horizontal scrolling for the edit link which is very confusing


![Image](https://user-images.githubusercontent.com/1443657/208197146-6a2e04d2-cb15-42b2-aa66-1b754c0a3fea.png)

**Comment by mveytsman** [comment]
Closed in https://github.com/bikebrigade/dispatch/commit/5a408e534b69bfbb3254e3a01f72d16235283f2d
