### ISSUE TITLE
Fix the location widget for problematic addresses

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#225]
@chadmohr Gave me a list which I won't be copying here for privacy reasons. I'll update this issue as I investigate.

**Comment by mveytsman** [comment]
It looks like the issue is in https://github.com/bikebrigade/dispatch/blob/main/lib/bike_brigade/geocoder/lib_lat_lon_geocoder.ex#L9 and the addresses that don't work.

We should 
- see if there's a better way to hint at regions than how we do it
- look into https://github.com/DaoDeCyrus/geocoder as an alternative to LibLatLon
- maybe some other heuristics around the input string?

**Comment by teesloane** [comment]
Looking at the google maps API, the only possibly helpful thing is adding a "component" that [hints to the country](https://developers.google.com/maps/documentation/geocoding/requests-geocoding#component-filtering). However, I haven't had much luck with this.

I have _however_, had luck with just appending "toronto" to every search query that doesn't automatically find it...and it just works. I will DM you a gif of this working.
