### ISSUE TITLE
Don't allow riders to unassign themselves within N hours of the delivery

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#294]
Right now you could unassign yourself from a task a minute before a delivery is scheduled. This will be an issue for dispatchers as people may just click that button last minute.

Within a certain time-period of the delivery start (to be determined in conversation with staff), riders should not be able to unassign themselves from the delivery. Instead they should be told to contact dispatch (currently via text message) to do so.

**Comment by sereprz** [comment]
- we can't prevent riders from unassign themselves
- open a modal to confirm that they want to unassign themselves and ask them to text the dispatch to let them know
- on mobile show an action button to "text dispatch"

**Comment by mveytsman** [comment]
We're going to do day of as the cut off

**Comment by mveytsman** [comment]
Closed in #375
