### ISSUE TITLE
Suppress campaigns from rider facing interface

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#300]
There are campaigns that are not open to all riders (Dixon Hall and West Neighbourhood house). Ideally, campaigns would have a checkbox to prevent them from displaying to all riders. 
![image](https://github.com/bikebrigade/dispatch/assets/1443657/6b6e94dd-6b85-48b1-87f4-767551c0d310)

**Comment by sereprz** [comment]
question: are the deliveries for Dixon Hall and West Neighbourhood house pre-assigned?

The checkbox takes care of the campaign not being shown to all riders, but should they be visible to *SOME* riders? or is that irrelevant because the same person does the certain deliveries all the time?

**Comment by sereprz** [comment]
okay! That makes it easier for now, tho I think it makes sense to think about how to handle "only these riders can see this campaigbn" case
cc @teesloane @mveytsman wdyt?

**Comment by chadmohr** [comment]
Rider tags?

**Comment by teesloane** [comment]
I'm not sure if i'm thinking of the same thing, but "only [A, B, C] riders can see campaigns [X, Y, Z]" as a feature could probably be accomplished with riders_tags (although I have not looked at that feature yet).

Other than that, I think we need to nonetheless start with making programs hideable from the delivery signup list.

**Comment by sereprz** [comment]
yeah I was thinking about it in terms of beta flags but I think that's kind of what rider tags are?

**Comment by mveytsman** [comment]
Every campaign should start turned off, and be opt-ed in over time as we enable it. 

launch date - every campaign is visible by default.

**Comment by sereprz** [comment]
This was closed in #328
