### ISSUE TITLE
Improve login expeirence on mobile

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#307]
As reported by rider Jaime, and a few other people we have an issue with logging in from mobile where if you leave the page and come back during login it reloads so you go 

1) Enter phone number
2) Get text
3) Switch to messages app to get code from text
4) Switch to browser 
5) page reloads and you're asked to enter your phone number again

There are two things to do here:

- [x] Make it so the code from bike brigade is automatically detected by the phone and pastable (I don't know how to do this)
- [ ] Make it so the page doesn't boot you from entering your phone number when it reloads.

**Comment by mveytsman** [comment]
Closing this via #368 
I haven't found a way to reproduce the reloading thing unfortunately  and neither has @chadmohr who had it happen.

Let's wait for a report to re-open this

**Comment by mveytsman** [comment]
Re-opening to set a cookie as a rider still has issues here

**Comment by chadmohr** [comment]
@mveytsman Jaime’s issue has been resolved and was a user thing. His iPhone, though old, prompted filling in the login code. I only teased him a little

**Comment by mveytsman** [comment]
Amazing!

I do think it will come up again though and makinbg the login screen more resiliant would help.

I've also realized that switching from a LiveView to a Controller/DeadView will fix it no need for fancy cookie magic
