### ISSUE TITLE
When programs no longer need riders

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#309]
This screenshot was taken at 6:30 pm, well after these campaigns are over. Ideally, campaigns would be considered full at their start time for the purposes of this call out. 

P.S. in this case, it is because deliveries were left in the campaign that were not needed this week so may not be a HUGE issue once leads do not leave folks in the campaign.
 
![image](https://github.com/bikebrigade/dispatch/assets/1443657/841cc849-cd7d-4e81-b9c6-4565b0c7425a)

**Comment by teesloane** [comment]
I will look into this, It's possible I built this so that the "next 48 hours" literally checks from the top of the current day to 48 hours from then, rather than 48 hours from `now`.
