### ISSUE TITLE
Recipient initials

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#337]
Is it possible to get the first letter and then any additional letters following a space from the name field for recipients on the rider facing signups? Looking at something like the attached, with one letter and without the crossroads, it takes me a surprising amount of time to figure out who is who, despite having worked with this list every week for over 2 years and having met all of these individuals :P

![image](https://github.com/bikebrigade/dispatch/assets/1443657/bfbee8dc-7ead-49c7-94c9-59eb45c3a2ff)

**Comment by teesloane** [comment]
To make sure I understand this correctly, are these correct examples of what the proposed change would look like:

| Rider name | What to display |
|--|-|
| Jane Doe | J D |
| Niki Brandon Doel | NBD|
| Carl Jo-Hansson | CJH|

**Comment by chadmohr** [comment]
YUP!
