### ISSUE TITLE
Displaying notes on signups - possible privacy concerns 

### ISSUE THREAD

**Issue by chadmohr** [bikebrigade/dispatch#340]
There are cases where names, contact info and even other personal info is put in notes. Basically, there could be anything in the notes. And these notes are displayed on desktops in the rider signups.
 
![Untitled](https://github.com/bikebrigade/dispatch/assets/34720/6e6dc646-38fb-4944-8004-893c29bdc98a)

**Comment by mveytsman** [comment]
This is a good catch!

Based on the convo in slack we'll hide these before signup. Cecily also suggested splitting up rider notes and signup notes in the future

@chadmohr I went ahead and edited the image to block the phone number, do you mind doing that in the future if you're uploading screenshots with private info?

**Comment by chadmohr** [comment]
Yes, for sure. This occurred to me after I posted.

**Comment by chadmohr** [comment]
Also, somewhere in here I am 99% sure I also suggested a signup notes box in addition to the delivery notes

**Comment by sereprz** [comment]
We're going to hide the column for now and revisit how to handle notes later on e.g. notes on signup VS notes on delivery

**Comment by chadmohr** [comment]
349 is closed. 

I don’t really understand the hesitation with the delivery and signup notes. Seems to me adding the latter solves a lot of problems.

**Comment by chadmohr** [comment]
@teesloane the notes bstill show on mobile 
![image](https://github.com/bikebrigade/dispatch/assets/1443657/bc0ac3b2-822c-4a36-87d9-2d0a486e37a7)
