### ISSUE TITLE
Text riders for campaigns that are switching on the Sunday

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#352]
Schedule for switching here: https://docs.google.com/spreadsheets/d/1U587z_EOU4m4WQ1kdTGBt8RKiqMXMBis94nx-KsX3XU/edit#gid=1462122027

Text the riders that have ridden in the last 90 days for the given program on the sunday that they switch.

Copy of text message to follow.

**Comment by sereprz** [comment]
Here's a template from Nathalie:

```
Howdy & heads up! Your Bike Bridage campaign is moving to the (awesome new!) Rider Portal this week. (Bye bye Google Sheets!) If you have any Qs or need any help, see: https://www.bikebrigade.ca/portal
```

My personal take is that we replace `Your Bike Brigade campaign` with the name of the campaign IF it's a quick thing that we can template. This is sending to the tutorial and I think that's okay? Or we could change it to `login using your phone number at [dispatch] or see check out a short tutorial at [https://www.bikebrigade.ca/portal]` or something to that effect

**Comment by mveytsman** [comment]
Set up all the messages as campaigns - added links to the spreadsheet here: https://docs.google.com/spreadsheets/d/1U587z_EOU4m4WQ1kdTGBt8RKiqMXMBis94nx-KsX3XU/edit#gid=1462122027
