### ISSUE TITLE
Format Elixir source with `mix format`?

### ISSUE THREAD

**Issue by danp** [bikebrigade/dispatch#394]
As a newcomer both to Elixir and this app, it would be very helpful to not have to worry too much about formatting.

I'm still getting my editor/etc setup going which should probably auto-format on save.

But it would be nice if `mix format` use was encouraged/enforced to ensure some baseline consistency.

For example running `mix format mix.exs "lib/**/*.{ex,exs}" "test/**/*.{ex,exs}"` as described in `mix help format` makes quite a few changes.

**Comment by mveytsman** [comment]
Good call. I have had mix format running on save before but have not consistently ran it as part of linting. 

I ran it in #396. 

Do you feel like we should add format as part of linting / a precommit hook?

**Comment by danp** [comment]
👍 I think enforcing it as part of CI would be great, along with tips in README/etc to suggest how to format locally before pushing.
