### ISSUE TITLE
Show how many deliveries a rider has made in the list on a campaign

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#415]
From Michelle

> Hi! Can I put in a feature request? It would be really helpful if there's a way to easily identify new (or newish - probably <5 deliveries ) riders on the campaign page. I try to keep a closer eye on new folks to make sure things go smoothly. Sometimes I'm not paying attention and don't notice there's a new name, and they can slip through the cracks. I constantly find myself looking up each user unless it's a regular. Would it be possible to add a little icon (or maybe a delivery count) to make this easier?

**Comment by neal-bpm** [comment]
Fixed and deployed in production.
