### ISSUE TITLE
Fix new rider form

### ISSUE THREAD

**Issue by drteeth** [bikebrigade/dispatch#8]
Is this functionality still needed? If nobody is missing it, I would assume we can delete it. If not, there are a number of problems with it:

- [ ] Form is not linked from any other part of the UI (You can get there by entering the url: `/riders/new`
- [ ] Attempting to save a new rider results in validation errors about city, province, postal, country, availability, all missing
- [ ] It's not possible to see these validation messages in the UI

**Comment by mveytsman** [comment]
Sorry I didn't realize you made issues here.

Right now we're pulling riders from the mailchimp signup. I'm good to cut the form
