### ISSUE TITLE
Add rider list returns only 10 riders when searching

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#93]
We should auto-paginate and return more riders as you scroll down the list. I'm not sure if I've implemented this anywhere else, but you want to do a second query if you scroll far enough down.

This comes into play when searching for a common name (e.g. "Alex")

**Comment by mveytsman** [comment]
@ShayMatasaro I'll explain more about this issue later today!

**Comment by ShayMatasaro** [comment]
notes:
looks like this is handled by  BikeBrigadeWeb.Components.RiderSelectionComponent which uses BikeBrigade.Riders.RiderSearch
checking fetch_page({%RiderSearch{page_changed: true}

**Comment by ShayMatasaro** [comment]
got temporary paging working with a custom button , now working on connecting phx-hook

**Comment by mveytsman** [comment]
Closed in #117 by @ShayMatasaro
