### ISSUE TITLE
Programs/index: New button is not visible when window is narrow

### ISSUE THREAD

**Issue by mveytsman** [bikebrigade/dispatch#96]
New button is cut off and theres no scroll bar

<img width="835" alt="Screen Shot 2022-04-29 at 10 53 47 AM" src="https://user-images.githubusercontent.com/34720/165969447-5a37937b-3ff1-43ac-9621-c12f050e0701.png">

We had this same problem with campaigns/index, should look there for guidance

**Comment by teesloane** [comment]
This appears to have been fixed. Closing!

![CleanShot 2023-10-31 at 06 18 45](https://github.com/bikebrigade/dispatch/assets/12987958/0025552b-3c0d-4caf-bc2c-20efe5237140)

**Comment by mveytsman** [comment]
🎉
